entity active_storage_attachments {
  * id : bigint(20)
  --
  * name : varchar(255)
  * record_type : varchar(255)
  * record_id : bigint(20)
  * blob_id : bigint(20)
  * created_at : datetime
  --
  - idx_active_storage_attachments_uniqueness (record_type, record_id, name, blob_id)
  idx_active_storage_attachments_on_blob_id (blob_id)
}

entity active_storage_blobs {
  * id : bigint(20)
  --
  * key : varchar(255)
  * filename : varchar(255)
  content_type : varchar(255)
  metadata : text
  * byte_size : bigint(20)
  * checksum : varchar(255)
  * created_at : datetime
  --
  - idx_active_storage_blobs_on_key (key)
}

entity admin_users {
  * id : bigint(20)
  --
  * provider : varchar(255)
  * uid : varchar(255)
  * sign_in_count : int(11)
  current_sign_in_at : datetime
  last_sign_in_at : datetime
  current_sign_in_ip : varchar(255)
  last_sign_in_ip : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  - idx_admin_users_on_omniauthable (provider, uid)
}

entity areable_code_zip_codes {
  * id : bigint(20)
  --
  areable_type : varchar(255)
  areable_code_id : bigint(20)
  zip_code_id : bigint(20)
  start_version_id : bigint(20)
  end_version_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_areable_code_zip_codes_on_zip_code_id (zip_code_id)
  index_areable_code_zip_codes_on_start_version_id (start_version_id)
  index_areable_code_zip_codes_on_end_version_id (end_version_id)
  index_areable_code_zip_codes_on_areable_type_and_areable_code_id (areable_type, areable_code_id)
}

entity areas {
  * id : bigint(20)
  --
  * name : varchar(255)
  * created_at : datetime
  * updated_at : datetime
}

entity area_active_prefecture_maps {
  * id : bigint(20)
  --
  * area_id : bigint(20)
  * prefecture_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_area_active_prefecture_maps_on_area_id (area_id)
  index_area_active_prefecture_maps_on_prefecture_id (prefecture_id)
}

entity brands {
  * id : bigint(20)
  --
  name : varchar(255)
  * created_at : datetime
  * updated_at : datetime
}

entity cities {
  * id : bigint(20)
  --
  * name : varchar(255)
  kana : varchar(255)
  prefecture_id : bigint(20)
  start_version_id : bigint(20)
  end_version_id : bigint(20)
  slug : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  - index_cities_on_slug (slug)
  index_cities_on_prefecture_id (prefecture_id)
  index_cities_on_start_version_id (start_version_id)
  index_cities_on_end_version_id (end_version_id)
}

entity city_average_prices {
  * id : int(11)
  --
  * city_id : bigint(20)
  * average_price : float
  * average_square_price : float
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_city_average_prices_on_city_id (city_id)
}

entity city_average_price_by_dates {
  * id : int(11)
  --
  * city_id : bigint(20)
  * constructed_in_year : int(11)
  * average_price : float
  * average_square_price : float
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_city_average_price_by_dates_on_city_id (city_id)
}

entity city_average_price_by_layouts {
  * id : int(11)
  --
  * city_id : bigint(20)
  * number_of_rooms : int(11)
  * layout_kind_id : int(11)
  * average_price : float
  * average_square_price : float
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_city_average_price_by_layouts_on_city_id (city_id)
}

entity city_codes {
  * id : bigint(20)
  --
  city_id : bigint(20)
  * code : varchar(255)
  start_version_id : bigint(20)
  end_version_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_city_codes_on_city_id (city_id)
  index_city_codes_on_start_version_id (start_version_id)
  index_city_codes_on_end_version_id (end_version_id)
  index_city_codes_on_code (code)
}

entity city_info_ages {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  average_age : int(11)
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_ages_city_id (city_id)
  idx_city_info_ages_prefecture_id (prefecture_id)
  idx_city_info_ages_grade_id (grade_id)
  idx_city_info_ages_area_id (area_id)
}

entity city_info_birthrates {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  birthrate : float
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_birthrate_city_id (city_id)
  idx_city_info_birthrate_prefecture_id (prefecture_id)
  idx_city_info_birthrate_grade_id (grade_id)
  idx_city_info_birthrate_area_id (area_id)
}

entity city_info_cares {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : bigint(20)
  care_homes : bigint(20)
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_cares_city_id (city_id)
  idx_city_info_cares_grade_id (grade_id)
  idx_city_info_cares_prefecture_id (prefecture_id)
  idx_city_info_cares_area_id (area_id)
}

entity city_info_crimes {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  crimes : bigint(20)
  population : bigint(20)
  crime_ratio_percentage : float
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_crimes_city_id (city_id)
  idx_city_info_crimes_grade_id (grade_id)
  idx_city_info_crimes_prefecture_rank (prefecture_rank)
  idx_city_info_crimes_prefecture_id (prefecture_id)
  idx_city_info_crimes_area_rank (area_rank)
}

entity city_info_households {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  households : bigint(20)
  owned_households : bigint(20)
  owned_percentage : float
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_households_city_id (city_id)
  idx_city_info_households_grade_id (grade_id)
  idx_city_info_households_prefecture_id (prefecture_id)
  idx_city_info_households_area_id (area_id)
}

entity city_info_incomes {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  taxpayers : bigint(20)
  total_income : bigint(20)
  average_income : bigint(20)
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_incomes_city_id (city_id)
  idx_city_info_incomes_prefecture_id (prefecture_id)
  idx_city_info_incomes_income_grade_id (grade_id)
  idx_city_info_incomes_area_id (area_id)
}

entity city_info_medicals {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : bigint(20)
  hospitals : bigint(20)
  clinics : bigint(20)
  beds : bigint(20)
  population : bigint(20)
  hospital_clinic_per_population : float
  hospital_clinic_prefecture_rank : int(11)
  hospital_clinic_area_rank : int(11)
  hospital_clinic_deviation : float
  hospital_clinic_grade_id : int(11)
  bed_per_population : float
  bed_prefecture_rank : int(11)
  bed_area_rank : int(11)
  bed_deviation : float
  bed_grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_medicals_city_id (city_id)
  idx_city_info_medicals_bed_grade_id (bed_grade_id)
  idx_city_info_medicals_hospital_clinic_grade_id (hospital_clinic_grade_id)
  idx_city_info_medicals_prefecture_id (prefecture_id)
  idx_city_info_medicals_area_id (area_id)
}

entity city_info_parks {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  parks : bigint(20)
  park_area : bigint(20)
  area_per_person : float
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_parks_city_id (city_id)
  idx_city_info_parks_grade_id (grade_id)
  idx_city_info_parks_prefecture_id (prefecture_id)
  idx_city_info_parks_area_id (area_id)
}

entity city_info_population_basics {
  * id : bigint(20)
  --
  city_id : bigint(20)
  prefecture_id : bigint(20)
  population : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_population_basics_city_id (city_id)
  idx_city_info_population_basics_prefecture_id (prefecture_id)
}

entity city_info_population_densities {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  population_density : float
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_population_densities_city_id (city_id)
  idx_city_info_population_densities_grade_id (grade_id)
  idx_city_info_population_densities_prefecture_id (prefecture_id)
  idx_city_info_population_densities_area_id (area_id)
}

entity city_info_population_growths {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : int(11)
  population_growth_percentage : float
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_population_growths_city_id (city_id)
  idx_city_info_population_growths_grade_id (grade_id)
  idx_city_info_population_growths_prefecture_id (prefecture_id)
  idx_city_info_population_growths_area_id (area_id)
}

entity city_info_population_under_fifteens {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * population : int(11)
  * under_fifteen_population : int(11)
  under_fifteen_population_percentage : float
  prefecture_rank : int(11)
  capital_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_population_under_fifteens_grade_id (grade_id)
  idx_city_info_population_under_fifteens_prefecture_id (prefecture_id)
  idx_city_info_population_under_fifteens_city_id (city_id)
}

entity city_info_school_highs {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : bigint(20)
  high_schools : bigint(20)
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_school_highs_city_id (city_id)
  idx_city_info_school_highs_prefecture_id (prefecture_id)
  idx_city_info_school_highs_grade_id (grade_id)
  idx_city_info_school_highs_area_id (area_id)
}

entity city_info_school_kindergartens {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : bigint(20)
  kindergartens : bigint(20)
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_school_kindergartens_city_id (city_id)
  idx_city_info_school_kindergartens_prefecture_id (prefecture_id)
  idx_city_info_school_kindergartens_grade_id (grade_id)
  idx_city_info_school_kindergartens_area_id (area_id)
}

entity city_info_school_middles {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : bigint(20)
  middle_schools : bigint(20)
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_school_middles_city_id (city_id)
  idx_city_info_school_middles_prefecture_id (prefecture_id)
  idx_city_info_school_middles_grade_id (grade_id)
  idx_city_info_school_middles_area_id (area_id)
}

entity city_info_school_middle_proceeds {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * jis_code : bigint(20)
  school_proceed : float
  national_school_proceed : int(11)
  private_school_proceed : int(11)
  proceed_ratio_percentage : float
  prefecture_rank : int(11)
  capital_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_middle_school_proceed_prefecture_id (prefecture_id)
  idx_city_info_middle_school_proceed_jis_code (jis_code)
  idx_city_info_middle_school_proceed_grade_id (grade_id)
  idx_city_info_middle_school_proceed_city_id (city_id)
}

entity city_info_school_primaries {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * prefecture_id : bigint(20)
  * area_id : bigint(20)
  primary_schools : bigint(20)
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_city_info_school_primaries_city_id (city_id)
  idx_city_info_school_primaries_prefecture_id (prefecture_id)
  idx_city_info_school_primaries_grade_id (grade_id)
  idx_city_info_school_primaries_area_id (area_id)
}

entity city_info_waiting_children {
  * id : bigint(20)
  --
  * prefecture_id : bigint(20)
  * city_id : bigint(20)
  * area_id : int(11)
  under_four_population : int(11)
  waiting_childs : int(11)
  waiting_childs_per_under_four_population : float
  prefecture_rank : int(11)
  area_rank : int(11)
  deviation : float
  grade_id : int(11)
  * updated_at : datetime
  * created_at : datetime
  --
  idx_city_info_households_city_id (city_id)
  idx_city_info_households_grade_id (grade_id)
  idx_city_info_households_prefecture_id (prefecture_id)
  idx_city_info_households_area_id (area_id)
}

entity city_itokuro_converts {
  * id : int(11)
  --
  city_id : bigint(20)
  itokuro_city_id : bigint(20)
}

entity city_neighbor_cities {
  * id : bigint(20)
  --
  city_id : bigint(20)
  neighbor_city_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_city_neighbor_citiess_on_city_id (city_id)
  index_city_neighbor_cities_on_neighbor_city_id (neighbor_city_id)
}

entity city_writings {
  * id : bigint(20)
  --
  city_id : bigint(20)
  * introduce : text
  * tips : text
  * recommend_area : text
  * traffic : text
  * recommend_spot : text
  * created_at : datetime
  * updated_at : datetime
  --
  index_city_codes_on_city_id (city_id)
}

entity latest_addresses {
  * id : bigint(20)
  --
  version_id : bigint(20)
  old_prefecture_id : bigint(20)
  old_prefecture_name : varchar(255)
  old_prefecture_kana : varchar(255)
  old_city_id : bigint(20)
  old_city_name : varchar(255)
  old_city_kana : varchar(255)
  old_town_id : bigint(20)
  old_town_name : varchar(255)
  old_town_kana : varchar(255)
  old_street_id : bigint(20)
  old_street_name : varchar(255)
  old_street_kana : varchar(255)
  latest_prefecture_id : bigint(20)
  latest_prefecture_name : varchar(255)
  latest_prefecture_kana : varchar(255)
  latest_city_id : bigint(20)
  latest_city_name : varchar(255)
  latest_city_kana : varchar(255)
  latest_town_id : bigint(20)
  latest_town_name : varchar(255)
  latest_town_kana : varchar(255)
  latest_street_id : bigint(20)
  latest_street_name : varchar(255)
  latest_street_kana : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  index_latest_addresses_on_version_id (version_id)
  index_latest_addresses_on_old_prefecture_id (old_prefecture_id)
  index_latest_addresses_on_old_city_id (old_city_id)
  index_latest_addresses_on_old_town_id (old_town_id)
  index_latest_addresses_on_old_street_id (old_street_id)
  index_latest_addresses_on_latest_prefecture_id (latest_prefecture_id)
  index_latest_addresses_on_latest_city_id (latest_city_id)
  index_latest_addresses_on_latest_town_id (latest_town_id)
  index_latest_addresses_on_latest_street_id (latest_street_id)
}

entity maddress_versions {
  * id : bigint(20)
  --
  * name : date
  * created_at : datetime
  * updated_at : datetime
}

entity mansion_access {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  station_id : bigint(20)
  line_id : bigint(20)
  group_code : bigint(20)
  station_name : varchar(255)
  station_line_name : varchar(255)
  station_walking_minutes : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_mansion_access_building_id (building_id)
  idx_mansion_access_station_id (station_id)
}

entity mansion_analytics_page_views {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * page_view : bigint(20)
  * start_date : datetime
  * end_date : datetime
  * created_at : datetime
  * updated_at : datetime
  --
  idx_mansion_analytics_page_views_on_building_id (building_id)
}

entity mansion_brand_maps {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * brand_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_mansion_brand_maps_on_building_id (building_id)
  index_mansion_brand_maps_on_brand_id (brand_id)
}

entity mansion_buildings {
  * id : bigint(20)
  --
  * unique_code : varchar(255)
  * name : varchar(255)
  * prefecture_id : int(11)
  * city_id : bigint(20)
  * town_id : bigint(20)
  street_id : bigint(20)
  block_number : varchar(255)
  * constructed_in : date
  ground_floor : int(11)
  underground_floor : int(11)
  unit_amount : int(11)
  * structure_id : int(11)
  construct_company : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  - idx_mansion_buildings_on_unique_code (unique_code)
  idx_mansion_buildings_on_name (name)
  idx_mansion_buildings_on_prefecture_id (prefecture_id)
  idx_mansion_buildings_on_city_id (city_id)
  idx_mansion_buildings_on_town_id (town_id)
  idx_mansion_buildings_on_street_id (street_id)
  idx_mansion_buildings_on_constructed_in (constructed_in)
}

entity mansion_displays {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * name : varchar(255)
  min_price : bigint(20)
  max_price : bigint(20)
  min_exclusive_area : float
  max_exclusive_area : float
  * number_of_rooms : int(11)
  * layout_kind_id : int(11)
  layout_name : varchar(255)
  * constructed_in : date
  age : bigint(20)
  ground_floor : int(11)
  unit_amount : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_mansion_displays_min_price (min_price)
  idx_mansion_displays_max_price (max_price)
  idx_mansion_displays_min_exclusive_area (min_exclusive_area)
  idx_mansion_displays_max_exclusive_area (max_exclusive_area)
  idx_mansion_displays_number_of_rooms (number_of_rooms)
  idx_mansion_displays_layout_kind_id (layout_kind_id)
  idx_mansion_displays_age (age)
  idx_mansion_displays_unit_amount (unit_amount)
  fk_mansion_displays_mansion_buildings_idx (building_id)
}

entity mansion_land_uses {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * land_use_zone_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_mansion_land_uses_on_zone_id (land_use_zone_id)
  index_mansion_land_uses_on_building_id (building_id)
}

entity mansion_primary_school_maps {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * school_id : bigint(20)
  --
  fk_mansion_primary_schools_mansion_buildings_idx (building_id)
  fk_mansion_primary_schools_primary_schools_idx (school_id)
}

entity mansion_sales_histories {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * mansion_research_id : bigint(20)
  * original_mansion_name : varchar(255)
  * sale_on : date
  * price : bigint(20)
  * square_price : bigint(20)
  * exclusive_area : float
  * layout_kind_id : int(11)
  * number_of_rooms : int(11)
  floor_number : int(11)
  opening_direction_id : int(11)
  * management_fee : int(11)
  management_company : varchar(255)
  management_form_id : int(11)
  * maintenance_fee : int(11)
  land_privilege_id : int(11)
  parking_kind_id : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_mansion_sales_histories_on_price (price)
  idx_mansion_sales_histories_on_sale_on (sale_on)
  index_mansion_sales_histories_on_building_id (building_id)
  idx_mansion_sales_histories_on_exclusive_area (exclusive_area)
}

entity mansion_search_words {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * value : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  index_mansion_search_words_on_building_id (building_id)
  fulltext_idx_mansion_search_words (value)
}

entity pinrich_lite_master_apartments {
  * id : bigint(20)
  --
  building_name : varchar(255)
  prefecture_name : varchar(255)
  location_name : varchar(255)
  location_name1 : varchar(255)
  location_name2 : varchar(255)
  town : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_pinrich_lite_master_apartments_on_building_name (building_name)
  idx_pinrich_lite_master_apartments_on_prefecture_name (prefecture_name)
  idx_pinrich_lite_master_apartments_on_location_name (location_name)
  idx_pinrich_lite_master_apartments_on_town (town)
  idx_pinrich_lite_master_apartments_on_location_name1 (location_name1)
  idx_pinrich_lite_master_apartments_on_location_name2 (location_name2)
}

entity prefectures {
  * id : bigint(20)
  --
  * name : varchar(255)
  * kana : varchar(255)
  region_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  slug : varchar(255)
  code : varchar(255)
  --
  - index_prefectures_on_slug (slug)
  index_prefectures_on_code (code)
  index_prefectures_on_region_id (region_id)
}

entity prefecture_average_prices {
  * id : int(11)
  --
  * prefecture_id : bigint(20)
  * average_price : float
  * average_square_price : float
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_prefecture_average_prices_on_prefecture_id (prefecture_id)
}

entity prefecture_average_price_by_layouts {
  * id : int(11)
  --
  * prefecture_id : bigint(20)
  * number_of_rooms : int(11)
  * layout_kind_id : int(11)
  * average_price : float
  * average_square_price : float
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_prefecture_average_price_by_layouts_on_prefecture_id (prefecture_id)
}

entity pricehubble_calculated_data_per_cities {
  * id : bigint(20)
  --
  * city_id : bigint(20)
  * date : date
  * year : int(11)
  * month : int(11)
  * living_area : double
  * sale_price : bigint(20)
  * sale_price_lower : bigint(20)
  * sale_price_upper : bigint(20)
  * sale_price_per_square : double
  * sale_price_per_tsubo : double
  * created_at : datetime
  * updated_at : datetime
  --
  fk_pricehubble_calculated_data_per_cities_cities_idx (city_id)
}

entity pricehubble_calculated_data_per_lines {
  * id : bigint(20)
  --
  * line_id : bigint(20)
  * date : date
  * year : int(11)
  * month : int(11)
  * living_area : double
  * sale_price : bigint(20)
  * sale_price_lower : bigint(20)
  * sale_price_upper : bigint(20)
  * sale_price_per_square : double
  * sale_price_per_tsubo : double
  * created_at : datetime
  * updated_at : datetime
  --
  fk_pricehubble_calculated_data_per_lines_railway_lines_idx (line_id)
}

entity pricehubble_calculated_data_per_prefectures {
  * id : bigint(20)
  --
  * prefecture_id : bigint(20)
  * date : date
  * year : int(11)
  * month : int(11)
  * living_area : double
  * sale_price : bigint(20)
  * sale_price_lower : bigint(20)
  * sale_price_upper : bigint(20)
  * sale_price_per_square : double
  * sale_price_per_tsubo : double
  * created_at : datetime
  * updated_at : datetime
  --
  fk_pricehubble_calculated_data_per_prefectures_prefectures_idx (prefecture_id)
}

entity pricehubble_calculated_data_per_stations {
  * id : bigint(20)
  --
  * group_code : int(11)
  * date : date
  * year : int(11)
  * month : int(11)
  * living_area : double
  * sale_price : bigint(20)
  * sale_price_lower : bigint(20)
  * sale_price_upper : bigint(20)
  * sale_price_per_square : double
  * sale_price_per_tsubo : double
  * created_at : datetime
  * updated_at : datetime
  --
  fk_pricehubble_calculated_data_per_stations_railway_stations_idx (group_code)
}

entity pricehubble_calculated_data_per_towns {
  * id : bigint(20)
  --
  * town_id : bigint(20)
  * date : date
  * year : int(11)
  * month : int(11)
  * living_area : double
  * sale_price : bigint(20)
  * sale_price_lower : bigint(20)
  * sale_price_upper : bigint(20)
  * sale_price_per_square : double
  * sale_price_per_tsubo : double
  * created_at : datetime
  * updated_at : datetime
  --
  fk_pricehubble_calculated_data_per_towns_idx (town_id)
}

entity pricehubble_dossiers {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * dossier_id : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  fk_pricehubble_dossiers_mansion_buildings_idx (building_id)
}

entity pricehubble_raw_data_per_buildings {
  * id : bigint(20)
  --
  * building_id : bigint(20)
  * date : date
  * year : int(11)
  * month : int(11)
  * living_area : double
  * sale_price : bigint(20)
  * sale_price_lower : bigint(20)
  * sale_price_upper : bigint(20)
  * sale_price_per_square : double
  * sale_price_per_tsubo : double
  * created_at : datetime
  * updated_at : datetime
  --
  fk_pricehubble_raw_data_per_buildings_mansion_buildings_idx (building_id)
}

entity primary_schools {
  * id : bigint(20)
  --
  * name : varchar(255)
  name_kana : varchar(255)
  prefecture_id : bigint(20)
  city_id : bigint(20)
  itokuro_city_id : bigint(20)
  address : varchar(255)
  minkou_url : varchar(255)
  * created_at : datetime
  * updated_at : datetime
}

entity primary_school_average_prices {
  * id : int(11)
  --
  * school_id : bigint(20)
  * average_price : float
  * average_square_price : float
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_primary_school_average_prices_on_school_id (school_id)
}

entity primary_school_average_price_by_layouts {
  * id : int(11)
  --
  * school_id : bigint(20)
  * number_of_rooms : int(11)
  * layout_kind_id : int(11)
  * average_price : float
  * average_square_price : float
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_primary_school_average_price_by_layouts_on_school_id (school_id)
}

entity primary_school_reviews {
  * id : bigint(20)
  --
  * school_id : bigint(20)
  * person_gender : tinyint(1)
  * title : varchar(255)
  * admmision_year : int(11)
  * general_rate : int(11)
  * general_text : text
  policy_rate : int(11)
  policy_text : text
  class_rate : int(11)
  class_text : text
  teacher_rate : int(11)
  teacher_text : text
  institution_rate : int(11)
  institution_text : text
  access_rate : int(11)
  access_text : text
  pta_rate : int(11)
  pta_text : text
  event_rate : int(11)
  event_text : text
  how_go_text : varchar(255)
  uniform_present : tinyint(1)
  uniform_text : text
  lunch_present : tinyint(1)
  lunch_text : text
  cost_text : text
  motivation_text : text
  proceed_text : varchar(255)
  proceed_reason_text : text
  * post_date : datetime
  * created_at : datetime
  * updated_at : datetime
  --
  idx_school_reviews_on_school_id (school_id)
}

entity railway_companies {
  * id : bigint(20)
  --
  * code : int(11)
  * name : varchar(255)
  * official_name : varchar(255)
  * short_name : varchar(255)
  * category_id : int(11)
  * status_id : int(11)
  * sort : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  - idx_railway_companies_on_code (code)
}

entity railway_lines {
  * id : bigint(20)
  --
  * company_id : bigint(20)
  * code : bigint(20)
  * msl_name : varchar(255)
  * master_name : varchar(255)
  * master_kana : varchar(255)
  * official_name : varchar(255)
  * status_id : int(11)
  * sort : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_railway_lines_name (master_name)
  idx_railway_lines_company_id (company_id)
}

entity railway_line_sorts {
  * id : bigint(20)
  --
  * line_id : bigint(20)
  * company_id : bigint(20)
  * line_sort : int(11)
  * company_sort : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_railway_line_sorts_line_id (line_id)
  idx_railway_line_sorts_company_id (company_id)
}

entity railway_line_writings {
  * id : bigint(20)
  --
  line_id : bigint(20)
  * introduce : text
  * tips : text
  * recommend_area : text
  * traffic : text
  * recommend_spot : text
  * created_at : datetime
  * updated_at : datetime
  --
  index_line_codes_on_line_id (line_id)
}

entity railway_stations {
  * id : bigint(20)
  --
  * line_id : bigint(20)
  * code : int(11)
  * group_code : int(11)
  msl_name : varchar(45)
  * master_name : varchar(255)
  * prefecture_id : int(11)
  * city_id : bigint(20)
  * status_id : int(11)
  * sort : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  - idx_railway_stations_on_code (code)
  idx_railway_stations_on_group_code (group_code)
  idx_railway_stations_on_prefecture_id (prefecture_id)
  idx_railway_stations_on_city_id (city_id)
  index_railway_stations_on_line_id (line_id)
}

entity railway_station_average_prices {
  * id : int(11)
  --
  * group_code : int(11)
  * average_price : float
  * average_square_price : float
  * buildings_count : int(11)
  * sales_histories_count : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  index_railway_station_average_prices_on_group_code (group_code)
}

entity railway_station_to_stations {
  * id : bigint(20)
  --
  * start_station_group_code : bigint(20)
  * end_station_group_code : bigint(20)
  * minutes : int(11)
  * transfer_time : int(11)
  * created_at : datetime
  * updated_at : datetime
  --
  idx_railway_station_to_stations_on_start_station_id (start_station_group_code)
  idx_railway_station_to_stations_on_end_station_id (end_station_group_code)
}

entity railway_station_writings {
  * id : bigint(20)
  --
  station_id : bigint(20)
  * introduce : text
  * tips : text
  * recommend_area : text
  * traffic : text
  * recommend_spot : text
  * created_at : datetime
  * updated_at : datetime
  --
  index_station_codes_on_station_id (station_id)
}

entity regions {
  * id : bigint(20)
  --
  * name : varchar(255)
  * created_at : datetime
  * updated_at : datetime
}

entity streets {
  * id : bigint(20)
  --
  name : varchar(255)
  kana : varchar(255)
  town_id : bigint(20)
  start_version_id : bigint(20)
  end_version_id : bigint(20)
  slug : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  - index_streets_on_slug (slug)
  index_streets_on_town_id (town_id)
  index_streets_on_start_version_id (start_version_id)
  index_streets_on_end_version_id (end_version_id)
}

entity street_codes {
  * id : bigint(20)
  --
  street_id : bigint(20)
  * code : varchar(255)
  start_version_id : bigint(20)
  end_version_id : bigint(20)
  * created_at : datetime(6)
  * updated_at : datetime(6)
  --
  index_street_codes_on_street_id (street_id)
  index_street_codes_on_start_version_id (start_version_id)
  index_street_codes_on_end_version_id (end_version_id)
  index_street_codes_on_code (code)
}

entity towns {
  * id : bigint(20)
  --
  name : varchar(255)
  kana : varchar(255)
  city_id : bigint(20)
  start_version_id : bigint(20)
  end_version_id : bigint(20)
  slug : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  - index_towns_on_slug (slug)
  index_towns_on_city_id (city_id)
  index_towns_on_start_version_id (start_version_id)
  index_towns_on_end_version_id (end_version_id)
}

entity town_codes {
  * id : bigint(20)
  --
  town_id : bigint(20)
  * code : varchar(255)
  start_version_id : bigint(20)
  end_version_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_town_codes_on_town_id (town_id)
  index_town_codes_on_start_version_id (start_version_id)
  index_town_codes_on_end_version_id (end_version_id)
  index_town_codes_on_code (code)
}

entity town_linked_buildings {
  * id : int(11)
  --
  * town_id : bigint(20)
  * linked_building_id : bigint(20)
  * linked_building_unique_code : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  index_town_linked_buildings_town_id (town_id)
  index_town_linked_stations_linked_building_id (linked_building_id)
  index_town_linked_stations_linked_building_unique_code (linked_building_id)
}

entity town_linked_search_conditions {
  * id : int(11)
  --
  * town_id : bigint(20)
  * name : varchar(255)
  * key : varchar(255)
  * value : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  index_town_linked_search_conditions_town_id (town_id)
}

entity town_linked_stations {
  * id : int(11)
  --
  * town_id : bigint(20)
  * linked_station_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_town_linked_stations_town_id (town_id)
  index_town_linked_stations_linked_station_id (linked_station_id)
}

entity town_linked_towns {
  * id : int(11)
  --
  * town_id : bigint(20)
  * linked_town_id : bigint(20)
  * created_at : datetime
  * updated_at : datetime
  --
  index_town_linked_towns_town_id (town_id)
  index_town_linked_towns_linked_town_id (linked_town_id)
}

entity town_writings {
  * id : bigint(20)
  --
  town_id : bigint(20)
  * introduce : text
  * tips : text
  * recommend_area : text
  * traffic : text
  * recommend_spot : text
  * created_at : datetime
  * updated_at : datetime
  --
  index_town_writings_on_town_id (town_id)
}

entity versions {
  * id : bigint(20)
  --
  * item_type : varchar(191)
  * item_id : bigint(20)
  * event : varchar(255)
  whodunnit : varchar(255)
  object : json
  object_changes : json
  created_at : datetime
  --
  index_versions_on_item_type_and_item_id (item_type, item_id)
}

entity zip_codes {
  * id : bigint(20)
  --
  code : varchar(255)
  * created_at : datetime
  * updated_at : datetime
  --
  - index_zip_codes_on_code (code)
}

active_storage_attachments }-- active_storage_blobs

areable_code_zip_codes }-- maddress_versions

areable_code_zip_codes }-- maddress_versions

areable_code_zip_codes }-- zip_codes

area_active_prefecture_maps }-- areas

area_active_prefecture_maps }-- prefectures

cities }-- prefectures

city_average_prices }-- cities

city_average_price_by_dates }-- cities

city_average_price_by_layouts }-- cities

city_codes }-- cities

city_info_ages }-- cities

city_info_birthrates }-- cities

city_info_cares }-- cities

city_info_crimes }-- cities

city_info_households }-- cities

city_info_incomes }-- cities

city_info_medicals }-- cities

city_info_parks }-- cities

city_info_population_basics }-- cities

city_info_population_densities }-- cities

city_info_population_growths }-- cities

city_info_population_under_fifteens }-- cities

city_info_school_highs }-- cities

city_info_school_kindergartens }-- cities

city_info_school_middles }-- cities

city_info_school_middle_proceeds }-- cities

city_info_school_primaries }-- cities

city_info_waiting_children }-- cities

city_neighbor_cities }-- cities

city_writings }-- cities

latest_addresses }-- cities

latest_addresses }-- prefectures

latest_addresses }-- streets

latest_addresses }-- towns

latest_addresses }-- cities

latest_addresses }-- prefectures

latest_addresses }-- streets

latest_addresses }-- towns

latest_addresses }-- maddress_versions

mansion_access }-- mansion_buildings

mansion_access }-- railway_stations

mansion_analytics_page_views }-- mansion_buildings

mansion_brand_maps }-- brands

mansion_brand_maps }-- mansion_buildings

mansion_displays }-- mansion_buildings

mansion_land_uses }-- mansion_buildings

mansion_primary_school_maps }-- mansion_buildings

mansion_primary_school_maps }-- primary_schools

mansion_sales_histories }-- mansion_buildings

mansion_search_words }-- mansion_buildings

prefectures }-- regions

prefecture_average_prices }-- prefectures

prefecture_average_price_by_layouts }-- prefectures

pricehubble_calculated_data_per_cities }-- cities

pricehubble_calculated_data_per_lines }-- railway_lines

pricehubble_calculated_data_per_prefectures }-- prefectures

pricehubble_calculated_data_per_stations }-- railway_stations

pricehubble_calculated_data_per_towns }-- towns

pricehubble_dossiers }-- mansion_buildings

pricehubble_raw_data_per_buildings }-- mansion_buildings

primary_school_average_prices }-- primary_schools

primary_school_average_price_by_layouts }-- primary_schools

primary_school_reviews }-- primary_schools

railway_lines }-- railway_companies

railway_line_sorts }-- railway_lines

railway_line_writings }-- railway_lines

railway_stations }-- railway_lines

railway_station_average_prices }-- railway_stations

railway_station_writings }-- railway_stations

streets }-- towns

towns }-- cities

towns }-- maddress_versions

towns }-- maddress_versions

town_codes }-- maddress_versions

town_codes }-- maddress_versions

town_codes }-- towns

town_linked_buildings }-- towns

town_linked_search_conditions }-- towns

town_linked_stations }-- towns

town_linked_towns }-- towns

town_writings }-- towns