require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - lib/**/*.{rb,rake}
    - spec/**/*.rb
    - db/**/*.schema
  Exclude:
    - Schemafile
    - Guardfile
    - vendor/**/*
    - bin/**
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - tmp/**/*
    - public/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: enable

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - test
    - development
    - staging
    - production

Rails/DynamicFindBy:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'config/sitemap.rb'
    - 'config/routes/**'
    - 'config/initializers/**'
    - 'factories/**/*'
    - 'spec/**/*'
    - 'config/environments/*'
    - '/**/*.schema'

Layout/LineLength:
  Max: 128

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Rails/FilePath:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'spec/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'

Layout/ParameterAlignment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - '/**/*.schema'

Layout/ExtraSpacing:
  AllowForAlignment: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/MultilineBlockChain:
  Enabled: false
